### ISSUE TITLE
DevTools problem in SSR

### ISSUE THREAD

**Issue by pom421** [bluebill1049/little-state-machine-dev-tools#3]
Hello, 

I use LSM in Next.js and the `DevTool` component doesn't seem to work correctly.

Here is a sandbox: https://codesandbox.io/s/bug-next-littlestatemachine-f4cwq

The sandbox is working online, but when I download it and make `yarn` and `yarn dev`, you will normally see the problem.

The error log is

```
/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/dist/index.js:1
import * as React from 'react';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.little-state-machine-devtools (/Users/pom/Downloads/f4cwq/.next/server/static/development/pages/_app.js:1544:18)
/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/dist/index.js:1
```

This is a server side routing problem only, because if I comment the lines mentionning DevTool in the _app.js file and uncomment them, the DevTool will eventually work, but it will fail again at the next hard refresh causing a server side refresh.

So, I don't know why in server side, babel doesn't seem to transpile the `import * as React` in ES5 syntax of the DevTool module.

**Comment by bluebill1049** [comment]
I will take a look at in the next couple of days.

**Comment by enpclark** [comment]
Also experiencing this same issue when trying to use the package in Next.js

**Comment by wmenegali** [comment]
Same problem here with Next.js

**Comment by sieliseiev** [comment]
Problem still exist.
Have Next.js with TS.
Next solutions have been tried:
1) [](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) ---> problems with TS
2) using const `withTM = require("next-transpile-modules")(["little-state-machine-devtools"]); module.exports = withTM({});` in next.config ---> not work for me, problem still exist.

**Comment by Dujota** [comment]
encountering this exact same problem. out of the box create next app crashes when LSM DevTools used

https://stackblitz.com/edit/nextjs-vo1yys?file=pages%2F_app.js

**Comment by marco-emmanuel-noto** [comment]
Second this, I have the same problem with SSR on Next.

**Comment by minorgod** [comment]
Hey @bluebill1049 , just wondering if you ever found a solution to this. I **_reeeally_** need this in my nextjs 12.x project. Wondering if there's some way to build the package differently to make it work? I tried importing the little-state-machine-devtool source into my project to see if building it with my app would work, but didn't have much luck with that either. If there's anything I can do to help figure it out please let me know.
